config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :users, only: [:index, :show] do
  #   resources :posts, only: [:index, :show]
  # end

  # get "/users/:user_id/posts", to: "posts#index", as: "user_posts"
  # get "/users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  # get "/users/:id", to: "users#show", as: "user"
  # get "/users", to: "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
   root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter_integer, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def update_post_counter
    user.update(posts_counter: user.posts.count)
  end

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def all_comments
    comments.order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, class_name: 'Post', foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:notice] = 'Comment successfully created!'
      redirect_to user_post_path(current_user, params[:post_id])
    else
      flash.now[:error] = 'Error: Error occurred when creating comment'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post_id: params[:post_id])
    @like.user_id = @user.id
    @like.post_id = params[:post_id]
    redirect_to user_post_path(@user, @post) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter_integer = 0
    if @post.save
      flash[:notice] = 'Post successfully created!'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Error: Error occurred when creating post'
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:id], user_id: params[:user_id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add new comments</h1>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </div>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="main-container">
	<div class="users-wrapper flex">
		<div class="img-cont">
    	<%= image_tag @user.photo, :size => "50x50", alt: "user photo" %>
		</div>
		<div class="user-details">
    	<h2><%= @user.name %></h2>
    	<p>Number of posts: <%= @user.posts_counter %></p>
		</div>
	</div>

	<% @posts.each do |post| %>
		<div class="posts-enclosure">
			<div class="users-post">
				<h2><%= link_to "Post title: #{post.title}", user_post_path(@user.id, post.id), class: "link-button" %></h2>
				<p><%= post.text %></p>
				<h4>Comments: <%=post.comments_counter %>, Likes: <%= post.likes_counter %></h4>
				<%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes" do |form| %>
    		    <%= form.submit "Like Post" %>
	       		<% end %>
			</div>
			<div class="comments-cont">
				<% if post.five_recent_comments.count.zero? %>
				<p>No comments on this post yet</p>
				<% else %>
				<% post.five_recent_comments.each do |comment| %>
				<p><%= comment.author.name %>: <%= comment.text %></p>
				<% end %>
				<% end %>
			</div>
		</div>
	<% end %>

<button class="pagination">Pagination</button>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</div>

	<div>
		<%= form.label :text %><br>
		<%= form.text_area :text %>
	</div>
	<%= form.submit "Click to Add Post"%>
<% end %>

app/views/posts/show.html.erb
<div class="main-container">
	<div class="post-container">
		<h2><%= @post.title %> by <%= @post.user.name %></h2>
		<h6>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter_integer %></h6>
		<p class="post-text"><%= @post.text %></p>
	</div>

	<div class="comments-cont">
		<% if @post.all_comments.count.zero? %>
		<p>Post has no comments yet</p>
		<%else%>
		<% @post.all_comments.each do |comment| %>
			<p><%= comment.user.name %>: <%= comment.text %></p>
		<% end %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="main-container flex">
<% @users.each do |user| %>
  <div class="users-wrapper flex">
    <div class="img-cont">
      <%= image_tag user.photo, :size => "50x50", alt: "user photo" %>
    </div>
    <div class="user-details">
      <h2><%= link_to user.name, user, class: "link-button"  %></h2>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
  </div>
<%end%>
</div>

app/views/users/show.html.erb
<div class="main-container flex">
<div class="users-wrapper flex">
   <div class="img-cont">
     <%= image_tag @user.photo, :size => "50x50", alt: "user photo" %>
   </div>
   <div class="user-details">
     <h2><%= @user.name %></h2>
     <p>Number of posts: <%= @user.posts_counter %></p>
   </div>
</div>

<div class="user-bio">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>

<div class="user-posts">
  <% if @user.three_posts.count.zero? %>
  <p>User has no posts yet</p>
  <% else %>
  <% @user.three_posts.each do |post| %>
    <div class="users-post">
      <h2><%= post.title %></h2>
      <p><%= post.text %></p>
      <h4>Comments: <%=post.comments_counter %>, Likes: <%= post.likes_counter_integer %></h4>
    </div>
    <% end %>
   <% end %>

   <button>
     <%= link_to "See all posts", user_posts_path(@user), class: "link-button" %>
   </button>
<div>
</div>